LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE:=game_static
MY_SRC_BASE_PATH:=../src/
MY_SRC_FILES:=\
$(MY_SRC_BASE_PATH)/game.c
LOCAL_SRC_FILES:=$(MY_SRC_FILES)
MY_C_INCLUDES:=\
$(LOCAL_PATH)/$(MY_SRC_BASE_PATH)
LOCAL_EXPORT_C_INCLUDES:=$(MY_C_INCLUDES)
LOCAL_C_INCLUDES:=$(MY_C_INCLUDES)
LOCAL_CFLAGS += -Wno-psabi
LOCAL_EXPORT_CFLAGS += -Wno-psabi
LOCAL_LDLIBS:=-lGLESv2
include $(BUILD_STATIC_LIBRARY)